# Generated by Django 3.1.3 on 2020-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=51)),
                ('time', models.DateTimeField()),
                ('actuating_value', models.FloatField()),
                ('tilt_grav', models.FloatField(null=True)),
                ('set_point', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Data_logger_compression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0.1)),
                ('time', models.FloatField(default=300)),
                ('set_point', models.FloatField(default=0.1)),
                ('actuating_value', models.FloatField(default=1)),
                ('tilt_grav', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='Data_logger_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logfiles',
            fields=[
                ('filename', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
