# Generated by Django 3.1.3 on 2021-02-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20201206_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='test',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
